### ISSUE TITLE
Publish new release 0.24.0

### ISSUE THREAD

**Issue by DenisCarriere** [MartyWallace/PolyK#16]
Just published a new release `0.24.0`.

Could you test your applications that depend on it.

There's also an easy [CDN URL](https://unpkg.com/polyk/dist/polyk.js) that you can simply import into your HTML page.

```html
<script src="https://unpkg.com/polyk/dist/polyk.min.js"></script>
```

Also looks like the bower works.

```bash
$ bower install polyk -f
bower resolve       https://github.com/MartyWallace/PolyK.git#*
bower download      https://github.com/MartyWallace/PolyK/archive/0.24.0.tar.gz
bower extract       polyk#* archive.tar.gz
bower resolved      https://github.com/MartyWallace/PolyK.git#0.24.0
bower install       polyk#0.24.0

polyk#0.24.0 bower_components/polyk
```

Close this issue whenever you've successfully tested the bower build.

CC: @febeling @MartyWallace

**Comment by febeling** [comment]
I don't really use bower. Can anyone confirm we're good?
