### ISSUE TITLE
Is this a fork?

### ISSUE THREAD

**Issue by erikh2000** [MartyWallace/PolyK#18]
Could you clarify how the project is being maintained, and if it's a goal to go beyond Ivan's PolyK library that he distributes from http://polyk.ivank.net/ ? I imagine this is basically a copy of Ivan's original source licensed via MIT with tests added and maybe other improvements. It's nice to see it on Github and NPM, which I understand Ivan wasn't too keen to do.

Thank you for adding the tests. I wouldn't have considered using the library without seeing these.

**Comment by martywallace** [comment]
@erikh2000 Not sure how I missed your question for so long, but it's literally just on GitHub for the sake of package management support.
