### ISSUE TITLE
Publish npm package

### ISSUE THREAD

**Issue by febeling** [MartyWallace/PolyK#3]
Once #2 is merged, publish to registry.

**Comment by febeling** [comment]
@kuckir – actually, as PolyK's original author, what's your view of publishing to npm? Do you approve?

**Comment by photopea** [comment]
Hi, sure, why not. I have no experience with npm, but I have heard about it.

Currently, my web is the main distribution channel, so it is up to you to keep it up to date at the other places.

**Comment by kuckir** [comment]
Hi, sure, why not. I have no experience with npm, but I have heard about it.

Currently, my web is the main distribution channel, so it is up to you to keep it up to date at the other places.

**Comment by rowanwins** [comment]
Hi @febeling 

Wondering if you're intending on following through with publishing this to npm - I'd find that handy :)

Thanks

**Comment by febeling** [comment]
@rowanwins I've published 0.22.2 to the npm registry, help yourself! :)

**Comment by rowanwins** [comment]
Gday @febeling 

FYI I finally tried installing this via npm but get an error 
````
npm ERR! cb() never called!
````
I don't seem to get it installing other modules from npm so not sure what's going. Looks like others have reported similar issues for other packages, typical solutions include upgrading node, clean the cache etc etc, I've tried a bunch of these to no avail so not sure what's going on...

**Comment by febeling** [comment]
Which command is failing? And which version of npm and node do you use?

**Comment by kuckir** [comment]
You can also use it right from http://polyk.ivank.net/polyk.js

**Comment by rowanwins** [comment]
Hi @febeling 

Sorry that was a bit of a rubbish report wasn't it!

So Im running
````
npm install polyk
````
and the error I receive is
````
npm ERR! cb() never called!
````

@kuckir Unfortunately I need it distributed via npm so I can register it as a dependency in my package.json , I can possibly work around it but if there is an easier fix that would be better.

Im using node v7.4.0 and npm v3.10.3

Cheers

**Comment by febeling** [comment]
It no problem, but the info may be important. 

I can't check the coming days unfortunately. I don't know, but maybe somebody else can look into it.

**Comment by DenisCarriere** [comment]
Same issue here:

```
$ npm -v
3.10.10
$ node -v
v6.10.0
$ npm install polyk
npm ERR! cb() never called!
```

**Comment by DenisCarriere** [comment]
This library doesn't seem to be supported by NodeJS, tried to execute it.

```
$ node src/polyk.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'polyk'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at PolyK (/home/ubuntu/Github/PolyK/src/polyk.js:37:30)
    at Object.<anonymous> (/home/ubuntu/Github/PolyK/src/polyk.js:41:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

You shouldn't be including your browser factory code in your source code, that should be in your `dist/` created by either `rollup/browserify/webpack/gulp`.

**Should not be in source code >>**
```javascript
(function (root, factory) {
  if(typeof define === "function" && define.amd) {
    define(["polyk"], factory);
  } else if(typeof module === "object" && module.exports) {
    module.exports = factory(require("polyk"));
  } else {
    root.myModule = factory(root.postal);
  }
}(this, function(postal) {
```

**Comment by DenisCarriere** [comment]
@febeling The last commits on the `master` branch should be good for a new npm release. Hopefully we won't get this again:

```
$ npm install polyk
npm ERR! cb() never called!
```

**Comment by febeling** [comment]
I'm only with my phone these next few days and can't release, unfortunately. 

I'll try to add you to the package as maintainers, not sure how well that works from here.

**Comment by febeling** [comment]
So if Denis or Marty or someone else was up for it, i'd add you as a collaborator on npmjs. 

Please give me your username there in case.

**Comment by DenisCarriere** [comment]
@febeling awesome stuff, my npm username is [`deniscarriere`](https://www.npmjs.com/~deniscarriere)

**Comment by febeling** [comment]
@deniscarriere i've set you up on npmjs, now the floor is yours!
