### ISSUE TITLE
[Request] how to implement advanced slice with multiple line ？

### ISSUE THREAD

**Issue by sonygod** [MartyWallace/PolyK#4]
[Request] how to implement advanced slice with multiple line ？

https://cloud.githubusercontent.com/assets/748320/19797937/a4d377a6-9d20-11e6-872d-f977ac11690b.png

Slice ( p : Array, ax : Number, ay : Number, bx : Number, by : Number ):Array//current version

Slice ( p : Array, lines:Array):Array//hope version

**Comment by rowanwins** [comment]
+1  that would be awesome

**Comment by MartyWallace** [comment]
As I don't maintain this package your best bet is to [head over to the official discussion page](http://polyk.ivank.net/?p=discussion) for questions.
