### ISSUE TITLE
Add basic unit testing

### ISSUE THREAD

**Issue by DenisCarriere** [MartyWallace/PolyK#7]
For a geo-processing library, it would be nice to include some tests, even if they are very basic unit testing. At least it would show that the obvious test cases are covered and if someone has any issues with more complex scenarios they could simply just submit a PR with the test case failing.

I'm happy to help to build the initial tests using [`jest`](http://facebook.github.io/jest/) (preferred) or [`tape`](https://github.com/substack/tape).

**Comment by MartyWallace** [comment]
Math and geometry isn't a strong point of mine so the unit tests wouldn't be likely to assert anything valuable. Feel free to add your own. The frameworks I have experience with are Jasmine and Mocha/Chai but like I said, I won't be able to contribute much anyway.

**Comment by DenisCarriere** [comment]
@MartyWallace Thanks for the honest reply :+1: 

I submitted at least 1 test for now.

Does Ivan Kuckir maintain any of this library else where? or is this a private repo pulled down?

**Comment by MartyWallace** [comment]
As far as I am aware he has not updated the project in some time. I visit the [Disquss thread](http://polyk.ivank.net/?p=discussion) from time to time to see if there are any additions or changes to merge in.

**Comment by DenisCarriere** [comment]
👍 thanks for the info
