### ISSUE TITLE
Drop dist folder from source code

### ISSUE THREAD

**Issue by DenisCarriere** [MartyWallace/PolyK#8]
You don't need to publish your `dist/` folder in the GitHub repo, all the files published via npm can be accessed here https://unpkg.com/polyk@0.22.2/.

Add `dist` to your `.gitignore`.

Also noticed your `polyk-min.js` is not published.

https://unpkg.com/polyk@0.22.2/dist/

To make sure specific files are included in your npm publish package, you can specify in your `package.json`.

```json
  "files": [
    "index.js",
    "dist"
  ],
```

**Comment by MartyWallace** [comment]
It looks like your PR resolves this, just confirming?

**Comment by DenisCarriere** [comment]
@MartyWallace Not exactly, the files are still there in your GitHub repo, was waiting for that merge to send another PR (didn't want to create a PR conflict).

**Comment by DenisCarriere** [comment]
@MartyWallace I'm not too sure if that would break Bower support. We can leave it be for now.

Side topic: Bower is pretty much dead, [last commits were in 2016 Nov & July](https://github.com/bower/bower/commits/master), nowadays everyone is using [`yarn`](https://github.com/yarnpkg/yarn) & `npm` for local NodeJS installs or web friendly bundles hosted by https://unpkg.com/.

Honestly there's no reason to even support Bower, unless you have a legacy project you want to support.
